services:
  - type: web
    name: workknock-api
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: WHATSAPP_INSTANCE_ID
        sync: false
      - key: WHATSAPP_API_TOKEN
        sync: false
      - key: WHATSAPP_API_URL
        sync: false
      - key: WHATSAPP_BOT_PHONE
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
