import { Router } from 'express';
import * as ctrl from '../controllers/integrations.controller';
const router = Router();
router.get('/', ctrl.getIntegrations);
router.get('/bot-info', ctrl.getBotInfo);
router.post('/connect/whatsapp', ctrl.connectWhatsApp);
router.post('/connect/telegram', ctrl.connectTelegram);
router.put('/:type', ctrl.upsertIntegration);
router.post('/:type/toggle', ctrl.toggleIntegration);
router.delete('/:type', ctrl.deleteIntegration);
router.get('/notifications', ctrl.getNotifications);
router.post('/notifications/read', ctrl.markNotificationsRead);
export default router;
